version: "3"

services:
  # rails:
  #   build:
  #     context: .
  #     dockerfile: docker/rails/Dockerfile
  #   links:
  #     - postgres

  postgres:
    image: postgres:12.3
    container_name: postgres-12.3
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
